# Generated by Django 4.2.16 on 2024-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
