# Generated by Django 4.2.16 on 2024-10-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sales_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debittracking',
            old_name='Reason',
            new_name='type',
        ),
        migrations.AddField(
            model_name='debittracking',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
