# Generated by Django 4.2.16 on 2024-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_reason_debittracking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debittracking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
