# Generated by Django 4.2.16 on 2024-10-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_employee_address_employee_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='total_hours',
        ),
    ]
