# Generated by Django 4.2.16 on 2024-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_employeeattendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
